name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      # 📥 Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # ☕ Java for Sonar
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🔍 SonarQube Scan (optimized)
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=image-app
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 🐳 Build Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/image-app:latest .

      # 🛡️ Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      # 🔐 Scan Image
      - name: Trivy Scan
        run: |
          trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/image-app:latest

      # 📤 Login Docker Hub
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 🚀 Push Image
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/image-app:latest

  deploy:
    needs: build-scan-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker system prune -f
            docker pull ${{ secrets.DOCKER_USERNAME }}/image-app:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 80:80 --name myapp ${{ secrets.DOCKER_USERNAME }}/image-app:latest
